# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestIndiapresidentconstit():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_indiapresidentconstit(self):
    self.driver.get("http://legislative.gov.in/")
    self.driver.set_window_size(1324, 752)
    self.driver.find_element(By.LINK_TEXT, "Read more").click()
    self.driver.find_element(By.LINK_TEXT, "Download (34.7 MB)").click()
    #self.driver.find_element(By.LINK_TEXT, "Download (93.89 MB)").click()
    #self.driver.find_element(By.LINK_TEXT, "Download (59.08 MB)").click()
    #self.driver.find_element(By.LINK_TEXT, "Download (69.29 MB)").click()
    #self.driver.find_element(By.LINK_TEXT, "Download (219.83 KB)").click()
    #self.driver.find_element(By.LINK_TEXT, "Download (40.67 MB)").click()
    #self.driver.find_element(By.LINK_TEXT, "Download (11.55 MB)").click()
    #self.driver.find_element(By.LINK_TEXT, "Download (31.47 MB)").click()
 

